[package]
name = "fuzz-targets-afl"
version = "0.1.0"
authors = ["Patrick Ventuzelo <ventuzelo.patrick@gmail.com>"]
edition = "2018"

[dependencies]
fuzz-targets = {path = "../targets"}
afl = "0.8.0"
